using System;
using System.Collections.Generic;
using System.Linq;
using WebExpress.WebCore.Internationalization;
using WebExpress.WebCore.WebApplication;
using WebExpress.WebCore.WebComponent;
using WebExpress.WebCore.WebMessage;

namespace WebExpress.WebCore.WebEndpoint
{
    /// <summary>
    /// The endpoint manager manages WebExpress elements, which can be called with a URI (Uniform Resource Identifier).
    /// </summary>
    public sealed class EndpointManager : IEndpointManager, ISystemComponent
    {
        private readonly IComponentHub _componentHub;
        private readonly IHttpServerContext _httpServerContext;
        private readonly Dictionary<Type, EndpointRegistration> _registrations = [];

        /// <summary>
        /// An event that fires when an endpoint is added.
        /// </summary>
        public event EventHandler<IEndpointContext> AddEndpoint;

        /// <summary>
        /// An event that fires when an endpoint is removed.
        /// </summary>
        public event EventHandler<IEndpointContext> RemoveEndpoint;

        /// <summary>
        /// Returns all endpoints contexts.
        /// </summary>
        public IEnumerable<IEndpointContext> Endpoints => _registrations.Values.SelectMany(x => x.EndpointsResolver());

        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        /// <param name="componentHub">The component hub.</param>
        /// <param name="httpServerContext">The reference to the context of the host.</param>
        private EndpointManager(IComponentHub componentHub, IHttpServerContext httpServerContext)
        {
            _componentHub = componentHub;

            _httpServerContext = httpServerContext;

            _httpServerContext.Log.Debug
            (
                I18N.Translate("webexpress.webcore:endpointmanager.initialization")
            );
        }

        /// <summary>
        /// Registers an endpoint context type.
        /// </summary>
        /// <typeparam name="T">The type of the endpoint context.</typeparam>
        /// <param name="endpointRegistration">The registration details containing the callback functions.</param>
        public void Register<T>(EndpointRegistration endpointRegistration) where T : IEndpointContext
        {
            var type = typeof(T);
            if (!_registrations.ContainsKey(type))
            {
                _registrations[type] = endpointRegistration;

                endpointRegistration.AddEndpoint += OnAddEndpoint;
                endpointRegistration.RemoveEndpoint += OnRemoveEndpoint;
            }
        }

        /// <summary>
        /// Removes the registration for a specific endpoint context type.
        /// </summary>
        /// <typeparam name="T">The type of the endpoint context.</typeparam>
        public void Remove<T>() where T : IEndpointContext
        {
            var type = typeof(T);
            _registrations.Remove(type, out var endpointRegistration);

            endpointRegistration.AddEndpoint -= OnAddEndpoint;
            endpointRegistration.RemoveEndpoint -= OnRemoveEndpoint;
        }

        //// <summary>
        /// Returns an enumeration of endpoint contexts.
        /// </summary>
        /// <param name="endpointType">The endpoint type.</param>
        /// <param name="applicationContext">The application context.</param>
        /// <returns>An enumeration of endpoint contexts.</returns>
        public IEnumerable<IEndpointContext> GetEndpoints(Type endpointType, IApplicationContext applicationContext = null)
        {
            if (endpointType == null)
            {
                return [];
            }

            return _registrations.SelectMany(x => x.Value.EndpointResolver(endpointType, applicationContext));
        }

        /// <summary>
        /// Handles a request and returns a response.
        /// </summary>
        /// <param name="request">The request to handle.</param>
        /// <param name="endpointContext">The context of the endpoint handling the request.</param>
        /// <returns>The response generated by the endpoint.</returns>
        public Response HandleRequest(Request request, IEndpointContext endpointContext)
        {
            var registration = _registrations
                .Where(x => x.Key == endpointContext?.GetType())
                .Select(x => x.Value)
                .FirstOrDefault();

            return registration?.HandleRequest(request, endpointContext);
        }

        /// <summary>
        /// Raises the event when an endpoint is added.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="endpointContext">The context of the endpoint being added.</param>
        private void OnAddEndpoint(object sender, IEndpointContext endpointContext)
        {
            AddEndpoint?.Invoke(sender, endpointContext);
        }

        /// <summary>
        /// Raises the event when an endpoint is removed.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="endpointContext">The context of the endpoint being removed.</param>
        private void OnRemoveEndpoint(object sender, IEndpointContext endpointContext)
        {
            RemoveEndpoint?.Invoke(sender, endpointContext);
        }

        /// <summary>
        /// Release of unmanaged resources reserved during use.
        /// </summary>
        public void Dispose()
        {
        }
    }
}
