name: Generate Documentation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Navigate to project directory
      working-directory: src/WebExpress.WebCore
      run: dotnet restore

    - name: Generate documentation
      working-directory: src/WebExpress.WebCore
      run: docfx build

    - name: Commit and push documentation
      run: |
        git add -f docs/
        git commit -m "Update documentation"
        git push
